#!/usr/bin/sh

openssl req -new -x509 -keyout /etc/adblocker/cert.pem -out /etc/adblocker/cert.pem -nodes -subj "/C=EX/ST=Example/L=Example/O=Example/OU=SSL/CN=example.com"

systemctl enable adblocker
systemctl start adblocker
